class Token_type() :
    EOF     =   0
    COMMAND =   1
    STRING =    2
    INTEGER =   3
    BOOL    =   4
    ASSIGN =    5
    COMPARE =   6
    PAR_OPEN =  7
    PAR_CLOSE = 8
    PARENT =    9
    ADD =       10
    SUB =       11
    MUL =       12
    DIV =       13
